import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import favicon from '../app/logo.png';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Netrum Dashboard - Le Huu Khoa",
  description: "Generated by create next app",
  icons: {
    icon: favicon.src, // Đường dẫn tính từ thư mục public
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
